#No language required so just use ruby to avoid warnings in travis yml linter
language: node_js
# dist: trusty
sudo: required

node_js:
  - "stable"

cache:
  directories:
    - node_modules # NPM packages

before_install:
  - sudo apt-get -qq update
    #calibre required for gitbook pdf
  - sudo apt-get install -y calibre

install:
  #- . $HOME/.nvm/nvm.sh
  #- nvm install stable
  #- nvm use stable
  #- npm install
  - npm install -g gitbook-cli

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: _book
  target_branch: gh-pages
  on:
    branch: master
