sudo: false
language: node_js
node_js:
    - 'stable'
cache:
    directories:
        - node_modules
notifications:
    email: false
branches:
    only:
        - master
env:
    global:
        - DEPLOY_BRANCH="master"
        - SOURCE_DIR="output"
        - TARGET_BRANCH="gh-pages"
        - SSH_KEY="id_rsa"
        - GIT_NAME="travis"
        - GIT_EMAIL="deploy@travis-ci.org"
script:
    - echo "Cloning gecko-dev can take some time"
    - travis_wait 30 npm run travis-render
after_success:
    - npm run travis-publish
before_install:
    - openssl aes-256-cbc -K $encrypted_71cd8ed3d44b_key -iv $encrypted_71cd8ed3d44b_iv
      -in id_rsa.enc -out id_rsa -d
